### ISSUE TITLE
PHP Fatal error:  Uncaught TypeError

### ISSUE THREAD

**Issue by Nicasso** [sebastianbergmann/phpcpd#156]
```
PHP Fatal error:  Uncaught TypeError: Return value of SebastianBergmann\PHPCPD\CLI\Application::disableXdebug() must be an instance of SebastianBergmann\PHPCPD\CLI\void, none returned in phar:///Users/nico/phpcpd.phar/src/CLI/Application.php:102
Stack trace:
#0 phar:///Users/nico/phpcpd.phar/src/CLI/Application.php(50): SebastianBergmann\PHPCPD\CLI\Application->disableXdebug()
#1 phar:///Users/nico/phpcpd.phar/symfony/console/Application.php(148): SebastianBergmann\PHPCPD\CLI\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 /Users/nico/phpcpd.phar(201): Symfony\Component\Console\Application->run()
#3 {main}
  thrown in phar:///Users/nico/phpcpd.phar/src/CLI/Application.php on line 102

Fatal error: Uncaught TypeError: Return value of SebastianBergmann\PHPCPD\CLI\Application::disableXdebug() must be an instance of SebastianBergmann\PHPCPD\CLI\void, none returned in phar:///Users/nico/phpcpd.phar/src/CLI/Application.php:102
Stack trace:
#0 phar:///Users/nico/phpcpd.phar/src/CLI/Application.php(50): SebastianBergmann\PHPCPD\CLI\Application->disableXdebug()
#1 phar:///Users/nico/phpcpd.phar/symfony/console/Application.php(148): SebastianBergmann\PHPCPD\CLI\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 /Users/nico/phpcpd.phar(201): Symfony\Component\Console\Application->run()
#3 {main}
  thrown in phar:///Users/nico/phpcpd.phar/src/CLI/Application.php on line 102
```

**Comment by sebastianbergmann** [comment]
The current version of PHPCPD requires PHP 7.1.

**Comment by Nicasso** [comment]
Ah, thanks!

**Comment by RiteshAryal** [comment]
Does this work with PHPv7.3 ? Because I'm still getting error.

`Fatal error: Uncaught Error: Call to undefined function xdebug_disable() in phar:///usr/bin/phpcpd/src/CLI/Application.php:98`
