### ISSUE TITLE
Uncaught TypeError in CLI\Command::execute()

### ISSUE THREAD

**Issue by pszalko** [sebastianbergmann/phpcpd#179]
I'm using the latest code from master branch with Symfony 5.0.2.
PHPCPD works fine and checks for duplicated code, but at the end it throws fatal error as follow:

```phpcpd 5.0-dev by Sebastian Bergmann.

No clones found.

Time: 90 ms, Memory: 4.00 MB
PHP Fatal error:  Uncaught TypeError: Return value of "SebastianBergmann\PHPCPD\CLI\Command::execute()" must be of the type int, NULL returned. in /webapps/vendor/symfony/console/Command/Command.php:258
Stack trace:
#0 /webapps/vendor/symfony/console/Application.php(924): Symfony\Component\Console\Command\Command->run()
#1 /webapps/vendor/symfony/console/Application.php(265): Symfony\Component\Console\Application->doRunCommand()
#2 /webapps/vendor/sebastian/phpcpd/src/CLI/Application.php(64): Symfony\Component\Console\Application->doRun()
#3 /webapps/vendor/symfony/console/Application.php(141): SebastianBergmann\PHPCPD\CLI\Application->doRun()
#4 /webapps/vendor/sebastian/phpcpd/phpcpd(51): Symfony\Component\Console\Application->run()
#5 {main}
  thrown in /webapps/vendor/symfony/console/Command/Command.php on line 258```

**Comment by migo315** [comment]
There is already an open PR for that.
