### ISSUE TITLE
v5.0.0 broken in phpcpd.phar

### ISSUE THREAD

**Issue by oddvalue** [sebastianbergmann/phpcpd#181]
`SebastianBergmann\PHPCPD\Detector\Detector::copyPasteDetection` expects arguments as int but command line arguments are passed as strings.

![image](https://user-images.githubusercontent.com/10127404/74930000-99feb480-53d4-11ea-985e-a6110c512d3c.png)

**Comment by sebastianbergmann** [comment]
Please do not post screenshots but paste output as text, please.

**Comment by bambamboole** [comment]
I am facing the very same issue.
```
php phpcpd.phar web/app/ --min-lines=5
 phpcpd 5.0.0 by Sebastian Bergmann.
 [20-Feb-2020 11:09:16 UTC] PHP Fatal error:  Uncaught TypeError: Argument 2 passed to SebastianBergmann\PHPCPD\Detector\Detector::copyPasteDetection() must be of the type int, string given, called in phar:///builds/datapump/backend/phpcpd.phar/src/CLI/Command.php on line 140 and defined in phar:///builds/datapump/backend/phpcpd.phar/src/Detector/Detector.php:35
 Stack trace:
 #0 phar:///builds/datapump/backend/phpcpd.phar/src/CLI/Command.php(140): SebastianBergmann\PHPCPD\Detector\Detector->copyPasteDetection(Array, '5', 70, false)
 #1 phar:///builds/datapump/backend/phpcpd.phar/symfony/console/Command/Command.php(255): SebastianBergmann\PHPCPD\CLI\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
 #2 phar:///builds/datapump/backend/phpcpd.phar/symfony/console/Application.php(925): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
 #3 phar:///builds/datapump/backend/phpcpd.phar/symfo in phar:///builds/datapump/backend/phpcpd.phar/src/Detector/Detector.php on line 35
 Fatal error: Uncaught TypeError: Argument 2 passed to SebastianBergmann\PHPCPD\Detector\Detector::copyPasteDetection() must be of the type int, string given, called in phar:///builds/datapump/backend/phpcpd.phar/src/CLI/Command.php on line 140 and defined in phar:///builds/datapump/backend/phpcpd.phar/src/Detector/Detector.php:35
 Stack trace:
 #0 phar:///builds/datapump/backend/phpcpd.phar/src/CLI/Command.php(140): SebastianBergmann\PHPCPD\Detector\Detector->copyPasteDetection(Array, '5', 70, false)
 #1 phar:///builds/datapump/backend/phpcpd.phar/symfony/console/Command/Command.php(255): SebastianBergmann\PHPCPD\CLI\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
 #2 phar:///builds/datapump/backend/phpcpd.phar/symfony/console/Application.php(925): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
 #3 phar:///builds/datapump/backend/phpcpd.phar/symfo in phar:///builds/datapump/backend/phpcpd.phar/src/Detector/Detector.php on line 35
 ERROR: Job failed: exit code 1
```

**Comment by sebastianbergmann** [comment]
I cannot reproduce the issue:
```
$ wget https://phar.phpunit.de/phpcpd.phar      
```
```
$ php phpcpd.phar /usr/local/src/phpunit
phpcpd 5.0.0 by Sebastian Bergmann.

Found 14 clones with 597 duplicated lines in 21 files:

  - /usr/local/src/phpunit/vendor/sebastian/diff/src/Output/StrictUnifiedDiffOutputBuilder.php:117-226 (109 lines)
    /usr/local/src/phpunit/vendor/sebastian/diff/src/Output/UnifiedDiffOutputBuilder.php:67-176

  - /usr/local/src/phpunit/vendor/phpdocumentor/reflection-docblock/src/DocBlock/Tags/Property.php:44-106 (62 lines)
    /usr/local/src/phpunit/vendor/phpdocumentor/reflection-docblock/src/DocBlock/Tags/PropertyRead.php:44-106

  - /usr/local/src/phpunit/vendor/sebastian/diff/src/Output/StrictUnifiedDiffOutputBuilder.php:230-284 (54 lines)
    /usr/local/src/phpunit/vendor/sebastian/diff/src/Output/UnifiedDiffOutputBuilder.php:178-232

  - /usr/local/src/phpunit/vendor/sebastian/comparator/tests/MockObjectComparatorTest.php:117-165 (48 lines)
    /usr/local/src/phpunit/vendor/sebastian/comparator/tests/ObjectComparatorTest.php:101-149

  - /usr/local/src/phpunit/tests/unit/Framework/AssertTest.php:2320-2362 (42 lines)
    /usr/local/src/phpunit/vendor/sebastian/comparator/tests/DateTimeComparatorTest.php:107-149

  - /usr/local/src/phpunit/vendor/sebastian/comparator/tests/DoubleComparatorTest.php:93-134 (41 lines)
    /usr/local/src/phpunit/vendor/sebastian/comparator/tests/NumericComparatorTest.php:82-123

  - /usr/local/src/phpunit/tests/_files/BankAccountTest.php:17-57 (40 lines)
    /usr/local/src/phpunit/tests/_files/BankAccountTest2.php:15-55

  - /usr/local/src/phpunit/vendor/phpdocumentor/reflection-docblock/src/DocBlock/Tags/Property.php:65-104 (39 lines)
    /usr/local/src/phpunit/vendor/phpdocumentor/reflection-docblock/src/DocBlock/Tags/Var_.php:66-105

  - /usr/local/src/phpunit/src/Framework/TestListener.php:22-59 (37 lines)
    /usr/local/src/phpunit/src/Framework/TestListenerDefaultImplementation.php:17-54

  - /usr/local/src/phpunit/vendor/phpdocumentor/reflection-docblock/src/DocBlock/Tags/Property.php:44-77 (33 lines)
    /usr/local/src/phpunit/vendor/phpdocumentor/reflection-docblock/src/DocBlock/Tags/PropertyWrite.php:44-77

  - /usr/local/src/phpunit/vendor/sebastian/diff/tests/Output/Integration/StrictUnifiedDiffOutputBuilderIntegrationTest.php:249-278 (29 lines)
    /usr/local/src/phpunit/vendor/sebastian/diff/tests/Output/Integration/UnifiedDiffOutputBuilderIntegrationTest.php:84-113

  - /usr/local/src/phpunit/vendor/phpdocumentor/reflection-docblock/src/DocBlock/Tags/Property.php:77-106 (29 lines)
    /usr/local/src/phpunit/vendor/phpdocumentor/reflection-docblock/src/DocBlock/Tags/PropertyWrite.php:77-106

  - /usr/local/src/phpunit/tests/_files/DataProviderDebugTest.php:16-38 (22 lines)
    /usr/local/src/phpunit/vendor/sebastian/exporter/tests/ExporterTest.php:32-54

  - /usr/local/src/phpunit/tests/unit/Util/ConfigurationTest.php:604-616 (12 lines)
    /usr/local/src/phpunit/tests/unit/Util/ConfigurationTest.php:624-636

0.48% duplicated lines out of 123665 total lines of code.
Average size of duplication is 42 lines, largest clone has 109 of lines

Time: 528 ms, Memory: 74.00 MB
```
What am I missing?

**Comment by bambamboole** [comment]
Update: 
This does not fail with PHP 7.2 but fails with PHP 7.4

**Comment by sebastianbergmann** [comment]
PHP 7.2 is dead (at least to me). PHPCPD 5 is not supported on PHP 7.2. I cannot reproduce this with PHP 7.4.

**Comment by RSpeekenbrink** [comment]
Same issue on PHP 7.3 gitlab runner:

```
 $ php phpcpd.phar app/ --min-lines=50
 phpcpd 5.0.0 by Sebastian Bergmann.
 Fatal error: Uncaught TypeError: Argument 2 passed to SebastianBergmann\PHPCPD\Detector\Detector::copyPasteDetection() must be of the type int, string given, called in phar:///builds/company/product/phpcpd.phar/src/CLI/Command.php on line 140 and defined in phar:///builds/company/product/phpcpd.phar/src/Detector/Detector.php:35
 Stack trace:
 #0 phar:///builds/company/product/phpcpd.phar/src/CLI/Command.php(140): SebastianBergmann\PHPCPD\Detector\Detector->copyPasteDetection(Array, '50', 70, false)
 #1 phar:///builds/company/product/phpcpd.phar/symfony/console/Command/Command.php(255): SebastianBergmann\PHPCPD\CLI\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
 #2 phar:///builds/company/product/phpcpd.phar/symfony/console/Application.php(925): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
 #3 phar:///builds/company/product/phpcpd.phar/symf in phar:///builds/company/product/phpcpd.phar/src/Detector/Detector.php on line 35
```

**Comment by lsv** [comment]
@sebastianbergmann you need to add --min-lines=10 to your command.

As described in my PR - when you type something in the command, it will be added as a string, as there are no type casting in ArgvInput
