### ISSUE TITLE
[5.0] Uncaught TypeError: Argument 2 passed to Detector::copyPasteDetection() must be of the type int, string given

### ISSUE THREAD

**Issue by lsv** [sebastianbergmann/phpcpd#182]
After 5.0 this `curl -OL https://phar.phpunit.de/phpcpd.phar && php phpcpd.phar src/ --min-lines=50` command does not work anymore.

PHP 7.4

```
PHP Fatal error:  Uncaught TypeError: Argument 2 passed to SebastianBergmann\PHPCPD\Detector\Detector::copyPasteDetection() must be of the type int, string given, called in phar:///home/lsv/Projects/phpcpd.phar/src/CLI/Command.php on line 140 and defined in phar:///home/lsv/Projects/phpcpd.phar/src/Detector/Detector.php:35
Stack trace:
#0 phar:///home/lsv/Projects/phpcpd.phar/src/CLI/Command.php(140): SebastianBergmann\PHPCPD\Detector\Detector->copyPasteDetection()
#1 phar:///home/lsv/Projects/phpcpd.phar/symfony/console/Command/Command.php(255): SebastianBergmann\PHPCPD\CLI\Command->execute()
#2 phar:///home/lsv/Projects/phpcpd.phar/symfony/console/Application.php(925): Symfony\Component\Console\Command\Command->run()
#3 phar:///home/lsv/Projects/phpcpd.phar/symfony/console/Application.php(265): Symfony\Component\Console\Application->doRunCommand()
#4 phar:///home/lsv/Projects/phpcpd.phar/src/CLI/Application.php(65) in phar:///home/lsv/Projects/phpcpd.phar/src/Detector/Detector.php on line 35
```

**Comment by lsv** [comment]
Dublicate of #181
